#:schema node_modules/wrangler/config-schema.json
name = "ai-audio-processing-cf"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
OPENAI_API_KEY = "production_value"

